version: '3'

services:
  ml-adac:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.gpu
    container_name: ml-adac
    image: ml-adac-image
    shm_size: '24gb'
    tty: true
    volumes: 
      - $PWD:/workspace
    command: '/bin/bash'
    ports:
      - 16181-16190:16181-16190
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]