version: '3'

services:
  ml-adac:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.gpu
    container_name: ml-adac
    image: ml-adac-image
    shm_size: '24gb'
    tty: true
    env_file:
      - .env
    volumes: 
      - $PWD:/workspace
    command: '/bin/bash'
    ports:
      - 18181-181190:18181-18190
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]